-- `S-2`, `S-16`, `S-17`.
--
-- Generated by drizzle-kit and then hand-edited, which is the standing rule in this folder: every
-- `ADD COLUMN … NOT NULL` below carries a DEFAULT, so Postgres applies it as a metadata-only fast
-- default instead of rewriting a populated table and aborting halfway. The one statement
-- drizzle-kit could not have written for itself is the backfill at the end.

CREATE TYPE "public"."task_scope" AS ENUM('contact', 'group', 'submission');--> statement-breakpoint

-- `S-2`. Three columns the brief has always asked for and that existed at no layer. Nullable, and
-- free text — see the note in `db/schema.ts` for why none of them is an enum.
ALTER TABLE "participant" ADD COLUMN "salutation" text;--> statement-breakpoint
ALTER TABLE "participant" ADD COLUMN "honorific" text;--> statement-breakpoint
ALTER TABLE "participant" ADD COLUMN "gender" text;--> statement-breakpoint

-- `S-16`. `contact` is the default on both tables, so every task and every assignment that already
-- exists keeps meaning exactly what it meant before this migration ran.
ALTER TABLE "task" ADD COLUMN "scope" "task_scope" DEFAULT 'contact' NOT NULL;--> statement-breakpoint
ALTER TABLE "task" ADD COLUMN "submission_id" uuid;--> statement-breakpoint
ALTER TABLE "task_assignment" ADD COLUMN "scope" "task_scope" DEFAULT 'contact' NOT NULL;--> statement-breakpoint
ALTER TABLE "task" ADD CONSTRAINT "task_submission_id_submission_id_fk" FOREIGN KEY ("submission_id") REFERENCES "public"."submission"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint

-- The uniqueness widening. Dropping first and rebuilding after is safe because the whole file runs
-- in one transaction, and no dedupe pass is needed in between: the constraint being dropped was
-- strictly *narrower* than the indexes replacing it, so every row that satisfied it already
-- satisfies them. `task_assignment_group_key` constrains nothing yet — no row can be `group`-scoped
-- until the application writes one.
ALTER TABLE "task_assignment" DROP CONSTRAINT "task_assignment_pair";--> statement-breakpoint
CREATE UNIQUE INDEX "task_assignment_contact_key" ON "task_assignment" USING btree ("task_id","participant_id") WHERE "task_assignment"."submission_id" is null;--> statement-breakpoint
CREATE UNIQUE INDEX "task_assignment_session_key" ON "task_assignment" USING btree ("task_id","participant_id","submission_id") WHERE "task_assignment"."submission_id" is not null;--> statement-breakpoint
CREATE UNIQUE INDEX "task_assignment_group_key" ON "task_assignment" USING btree ("task_id","submission_id") WHERE "task_assignment"."scope" = 'group';--> statement-breakpoint
CREATE INDEX "task_assignment_submission_idx" ON "task_assignment" USING btree ("submission_id");--> statement-breakpoint

-- The backfill, and the only statement here that changes data.
--
-- Before this migration `submission_id` was written on every non-manual assignment by picking the
-- participant's *first* accepted submission — an arbitrary one, and the bug `S-16` names. Those
-- rows are all `contact`-scoped now, and a contact-scoped row is about a person rather than a
-- session, so the arbitrary pointer is cleared.
--
-- This is not cosmetic. `reconcileAssignments` now diffs existing rows against targets on
-- `(participant_id, submission_id)`. A legacy row left pointing at a session it was never really
-- about would not match the `(participant, null)` target its own task now resolves to, and the next
-- time an organizer so much as renamed that task the row would be deleted and recreated — taking a
-- speaker's completed status, uploaded file ids and form answers with it.
--
-- Nothing is lost that was ever meaningful: the pointer was never chosen, and an organizer who
-- wants a task attached to a session can now say so with `task.scope` and `task.submission_id`.
UPDATE "task_assignment" SET "submission_id" = NULL
WHERE "submission_id" IS NOT NULL
  AND "task_id" IN (SELECT "id" FROM "task" WHERE "scope" = 'contact');
