// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`

interface CloudflareEnv {
	FILES: R2Bucket;
	NEXT_INC_CACHE_R2_BUCKET: R2Bucket;
	HYPERDRIVE: Hyperdrive;
	ASSETS: Fetcher;
}
