declare module '*.jpg' {
  const image: import('next/image').StaticImageData;
  export default image;
}

/**
 * The two global stylesheets `app/layout.tsx` imports for their side effect. TypeScript 7 checks
 * side-effect imports, and nothing declares a bare `.css` module: Next's own types cover
 * `*.module.css` only, and `next-env.d.ts` is generated by a build rather than committed, so
 * `bun run typecheck` cannot rely on it. The longer suffix wins, so this does not shadow the
 * per-class typing a CSS module import gets.
 */
declare module '*.css';
