/**
 * Validates docs/alternatives/data/ and regenerates every derived artifact from it.
 *
 *   bun run alternatives:build            rewrite the derived files
 *   bun run alternatives:build --check    fail if any of them is stale (this is the CI gate)
 *
 * The two JSON files under docs/alternatives/data/ are the only hand-maintained inputs. Everything
 * this writes is derived — do not hand-edit the outputs, they will be overwritten.
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';

import {
  ALTERNATIVES_DIR,
  COVERAGE_SYMBOL,
  REPO_ROOT,
  analyzed,
  extrasByProject,
  loadSurvey,
  summarize,
  validate,
  type Survey,
} from './survey';
import { renderVisual } from './visual';

const MATRIX_PATH = join(ALTERNATIVES_DIR, 'feature-matrix.md');
const SURVEY_JSON_PATH = join(ALTERNATIVES_DIR, 'data', 'survey.json');
const VISUAL_PATH = join(ALTERNATIVES_DIR, 'visual', 'index.html');
const REQUIREMENTS_PATH = join(REPO_ROOT, 'docs', '07-comparative-requirements.md');

const GENERATED_NOTE =
  '<!-- Generated by `bun run alternatives:build` from docs/alternatives/data/. Do not edit by hand. -->';

/** Replaces the body of each `<!-- generated:NAME -->` … `<!-- /generated:NAME -->` block. */
function applyGeneratedBlocks(source: string, blocks: Record<string, string>): string {
  let out = source;
  for (const [name, body] of Object.entries(blocks)) {
    const open = `<!-- generated:${name} -->`;
    const close = `<!-- /generated:${name} -->`;
    const start = out.indexOf(open);
    const end = out.indexOf(close);
    if (start === -1 || end === -1 || end < start) {
      throw new Error(`missing generated block "${name}" — expected ${open} … ${close}`);
    }
    out = `${out.slice(0, start + open.length)}\n${body}\n${out.slice(end)}`;
  }
  return out;
}

function renderMatrix(survey: Survey): string {
  const projects = analyzed(survey);
  const header = ['Feature', 'Cicero', ...projects.map((p) => p.project)];
  const lines = [
    `| ${header.join(' | ')} |`,
    `|${header.map((_, i) => (i === 0 ? '---' : ':-:')).join('|')}|`,
  ];

  const row = (label: string, cicero: string, cells: string[]) =>
    `| ${label} | ${cicero} | ${cells.join(' | ')} |`;

  lines.push(row(`**Baseline (${survey.features.areas.length})**`, '', projects.map(() => '')));
  for (const area of survey.features.areas) {
    lines.push(
      row(
        `${area.id} · ${area.label}`,
        COVERAGE_SYMBOL.full,
        projects.map((p) => COVERAGE_SYMBOL[p.coverage![area.id]]),
      ),
    );
  }

  lines.push(row(`**Beyond the brief (${survey.features.extras.length})**`, '', projects.map(() => '')));
  for (const extra of survey.features.extras) {
    const shipped = new Set(extra.projects);
    lines.push(
      row(
        `${extra.id} · ${extra.title}`,
        COVERAGE_SYMBOL.absent,
        projects.map((p) => (shipped.has(p.slug) ? COVERAGE_SYMBOL.full : '')),
      ),
    );
  }

  lines.push(
    row(`**Cicero capabilities (${survey.features.ciceroDifferentiators.length})**`, '', projects.map(() => '')),
  );
  for (const cd of survey.features.ciceroDifferentiators) {
    lines.push(
      row(
        `${cd.id} · ${cd.title}`,
        COVERAGE_SYMBOL.full,
        projects.map((p) =>
          cd.derivedFromArea ? COVERAGE_SYMBOL[p.coverage![cd.derivedFromArea]] : COVERAGE_SYMBOL.unknown,
        ),
      ),
    );
  }

  const stats = summarize(survey);
  return [
    '# Full feature matrix',
    '',
    GENERATED_NOTE,
    '',
    `Every feature row against every analyzed project. ${stats.counts.totalFeatureRows} rows ×`,
    `${projects.length} projects, unfiltered — nothing is dropped for being rare.`,
    '',
    `\`${COVERAGE_SYMBOL.full}\` shipped · \`${COVERAGE_SYMBOL.partial}\` partial · ` +
      `\`${COVERAGE_SYMBOL.absent}\` absent · \`${COVERAGE_SYMBOL.unknown}\` not determined`,
    '',
    'In the baseline band every cell was verified in source. In the beyond-the-brief band a blank',
    'cell means the capability was **not attributed** to that project, which is weaker than a',
    'verified absence — those rows were built by reading what each project *added*, not by checking',
    'all 48 against all 32. The Cicero band records field-wide counts; only the three rows with a',
    'matching baseline area carry real per-project values.',
    '',
    'A browsable version of this same grid lives at `docs/alternatives/visual/index.html`.',
    '',
    ...lines,
    '',
  ].join('\n');
}

function renderRequirementBlocks(survey: Survey): Record<string, string> {
  const projects = analyzed(survey);
  const byProject = extrasByProject(survey);
  const nameOf = (slug: string) => projects.find((p) => p.slug === slug)?.project ?? slug;

  const tiers = [...new Set(survey.features.extras.map((e) => e.tier))];
  const requirements = tiers
    .map((tier) => {
      const items = survey.features.extras
        .filter((e) => e.tier === tier)
        .sort((a, b) => b.convergence - a.convergence || a.id.localeCompare(b.id));
      const body = items
        .map(
          (e) =>
            `#### ${e.id} — ${e.title}\n\n${e.description}\n\n` +
            `**Independent arrivals:** ${e.convergence} of ${projects.length} · ` +
            `**Built by:** ${e.projects.map(nameOf).join(', ')}\n`,
        )
        .join('\n');
      return `### ${tier}\n\n${body}`;
    })
    .join('\n');

  const baseline = [
    '| Area | Full | Partial | Absent |',
    '|---|--:|--:|--:|',
    ...survey.features.areas.map((area) => {
      const cells = projects.map((p) => p.coverage![area.id]);
      const count = (v: string) => cells.filter((c) => c === v).length;
      return `| ${area.label} | ${count('full')} | ${count('partial')} | ${count('absent')} |`;
    }),
  ].join('\n');

  const perProject = [
    '| Project | Beyond-the-brief features | Baseline areas cleared |',
    '|---|--:|--:|',
    ...projects
      .map((p) => ({
        p,
        extras: (byProject.get(p.slug) ?? []).length,
        full: Object.values(p.coverage!).filter((v) => v === 'full').length,
      }))
      .sort((a, b) => b.extras - a.extras || a.p.project.localeCompare(b.p.project))
      .map((r) => `| ${r.p.project} | ${r.extras} | ${r.full}/${survey.features.areas.length} |`),
  ].join('\n');

  const differentiators = [
    '| ID | Capability | Absent in |',
    '|---|---|--:|',
    ...survey.features.ciceroDifferentiators.map(
      (cd) => `| ${cd.id} | ${cd.title} | ${cd.absentIn}/${cd.of} |`,
    ),
  ].join('\n');

  return { requirements, baseline, 'per-project': perProject, differentiators };
}

const REQUIREMENTS_SCAFFOLD = `# Comparative requirements

${GENERATED_NOTE.replace('Generated by', 'The tables and the numbered list below are generated by')}

Where \`docs/01-requirements.md\` and \`docs/05-additional-requirements.md\` record what *we* decided to
build, this file records what the rest of the field actually built. Every item is derived from
reading another entrant's source at a pinned commit — see \`docs/alternatives/\` for the per-project
notes and \`docs/alternatives/feature-matrix.md\` for the full grid.

These are observations, not a backlog. Nothing here is committed work, and nothing here is a
judgment about the projects it came from. Convergence is the only ranking signal used: a capability
several teams reached independently, from the same brief and without coordinating, is better
evidence that the brief implies it than one team's clever idea.

## How to read it

- **AD-n** — a capability shipped by at least one analyzed project and absent from Cicero.
- **Independent arrivals** — how many of the analyzed projects built it. This is the tiering key.
- Attribution is positive-only. An absent attribution means the capability was not recorded for
  that project, not that it was verified missing there.

## Baseline coverage across the field

<!-- generated:baseline -->
<!-- /generated:baseline -->

## What each project added

<!-- generated:per-project -->
<!-- /generated:per-project -->

## The requirements

<!-- generated:requirements -->
<!-- /generated:requirements -->

## Cicero capabilities the field mostly lacks

Recorded for symmetry — the same reading pass that produced the list above produced this one.

<!-- generated:differentiators -->
<!-- /generated:differentiators -->
`;

function writeOut(path: string, content: string, check: boolean, stale: string[]): void {
  const rel = relative(REPO_ROOT, path);
  let current: string | null = null;
  try {
    current = readFileSync(path, 'utf8');
  } catch {
    current = null;
  }
  if (current === content) return;
  if (check) {
    stale.push(current === null ? `${rel} is missing` : `${rel} is out of date`);
    return;
  }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content, 'utf8');
  console.log(`  wrote ${rel}`);
}

function main(): void {
  const check = process.argv.includes('--check');
  const survey = loadSurvey();

  const problems = validate(survey);
  if (problems.length > 0) {
    console.error(`docs/alternatives/data/ is inconsistent (${problems.length} problems):`);
    for (const problem of problems) console.error(`  - ${problem}`);
    process.exit(1);
  }

  const stats = summarize(survey);
  let requirementsSource: string;
  try {
    requirementsSource = readFileSync(REQUIREMENTS_PATH, 'utf8');
  } catch {
    requirementsSource = REQUIREMENTS_SCAFFOLD;
  }

  const stale: string[] = [];
  writeOut(SURVEY_JSON_PATH, `${JSON.stringify(stats, null, 2)}\n`, check, stale);
  writeOut(MATRIX_PATH, renderMatrix(survey), check, stale);
  writeOut(VISUAL_PATH, renderVisual(survey), check, stale);
  writeOut(
    REQUIREMENTS_PATH,
    applyGeneratedBlocks(requirementsSource, renderRequirementBlocks(survey)),
    check,
    stale,
  );

  if (check) {
    if (stale.length > 0) {
      console.error('Derived files are stale — run `bun run alternatives:build` and commit the result:');
      for (const item of stale) console.error(`  - ${item}`);
      process.exit(1);
    }
    console.log(`alternatives: data valid and all derived files current (${stats.counts.analyzed} projects).`);
    return;
  }

  console.log(
    `alternatives: ${stats.counts.analyzed} analyzed of ${stats.counts.submissionsFound} found · ` +
      `${stats.counts.totalFeatureRows} feature rows · ${stats.counts.attributions} attributions.`,
  );
}

main();
