export type RomanAssetCategory = "places" | "artifacts" | "materials";

export interface RomanAsset {
  id: string;
  name: string;
  path: string;
  category: RomanAssetCategory;
  orientation: "landscape" | "portrait" | "square" | "panorama";
  alt: string;
  focalPoint: string;
  recommendedFor: readonly string[];
  source: {
    title: string;
    pageUrl: string;
    author: string;
    license: string;
    licenseUrl: string;
    originalDimensions: string;
    accuracyNote?: string;
  };
}

export const ROMAN_ASSETS = [
  {
    id: "constantine-colosseum",
    name: "Colosseum from the Palatine",
    path: "/assets/roman/places/constantine-colosseum.webp",
    category: "places",
    orientation: "landscape",
    alt: "The Colosseum and Arch of Constantine seen across the ruins of the Palatine Hill.",
    focalPoint: "49% 44%",
    recommendedFor: ["primary hero", "event landing page", "wide banner"],
    source: {
      title: "Colosseum and Arch of Constantine seen from Palatine",
      pageUrl:
        "https://commons.wikimedia.org/wiki/File:Colosseum_and_Arch_of_Constantine_seen_from_Palatine.jpg",
      author: "Livioandronico2013",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      originalDimensions: "5688 × 4000",
    },
  },
  {
    id: "colosseum-forum",
    name: "Colosseum and Forum",
    path: "/assets/roman/places/colosseum-forum.webp",
    category: "places",
    orientation: "landscape",
    alt: "The Colosseum rising beyond Roman Forum ruins and dark green cypress trees.",
    focalPoint: "44% 47%",
    recommendedFor: ["hero", "conference overview", "editorial banner"],
    source: {
      title: "Colosseum of Rome and Roman forum",
      pageUrl:
        "https://commons.wikimedia.org/wiki/File:Colosseum_of_Rome_and_Roman_forum.jpg",
      author: "Wilfredor",
      license: "CC0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
      originalDimensions: "7316 × 4330",
    },
  },
  {
    id: "appian-way",
    name: "The Appian Way",
    path: "/assets/roman/places/appian-way.webp",
    category: "places",
    orientation: "landscape",
    alt: "A long section of the Appian Way framed by umbrella pines, meadow grass, and low ruins.",
    focalPoint: "50% 48%",
    recommendedFor: ["journey theme", "agenda cover", "quiet hero"],
    source: {
      title: "Appian Way",
      pageUrl: "https://commons.wikimedia.org/wiki/File:Appian_Way.jpg",
      author: "Livioandronico2013",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      originalDimensions: "6016 × 4000",
    },
  },
  {
    id: "via-appia-stones",
    name: "Via Appia paving",
    path: "/assets/roman/places/via-appia-stones.webp",
    category: "places",
    orientation: "portrait",
    alt: "Ancient basalt paving stones on the Via Appia running between trees and old walls.",
    focalPoint: "50% 62%",
    recommendedFor: ["portrait panel", "road motif", "mobile background"],
    source: {
      title: "Via Appia",
      pageUrl: "https://commons.wikimedia.org/wiki/File:Via_appia.jpg",
      author: "Kleuske",
      license: "CC BY-SA 3.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
      originalDimensions: "1704 × 2272",
    },
  },
  {
    id: "appian-aqueduct",
    name: "Aqueduct along the Appian Way",
    path: "/assets/roman/places/appian-aqueduct.webp",
    category: "places",
    orientation: "landscape",
    alt: "A Roman aqueduct crossing a green field beside the Appian Way.",
    focalPoint: "47% 41%",
    recommendedFor: [
      "infrastructure story",
      "agenda section",
      "panoramic card",
    ],
    source: {
      title: "Via Appia - acquedotti 1010299",
      pageUrl:
        "https://commons.wikimedia.org/wiki/File:Via_Appia_-_acquedotti_1010299.JPG",
      author: "Lalupa",
      license: "CC BY-SA 3.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
      originalDimensions: "2816 × 2112",
    },
  },
  {
    id: "pont-du-gard",
    name: "Pont du Gard",
    path: "/assets/roman/places/pont-du-gard.webp",
    category: "places",
    orientation: "panorama",
    alt: "The three tiers of the Pont du Gard aqueduct spanning a rocky river valley.",
    focalPoint: "50% 48%",
    recommendedFor: [
      "ultrawide hero",
      "section divider",
      "infrastructure theme",
    ],
    source: {
      title: "Pont du Gard 2017",
      pageUrl: "https://commons.wikimedia.org/wiki/File:Pont_du_Gard_2017.jpg",
      author: "Wolfgang Moroder",
      license: "CC BY-SA 3.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
      originalDimensions: "15000 × 6663",
    },
  },
  {
    id: "roman-forum",
    name: "Roman Forum panorama",
    path: "/assets/roman/places/roman-forum.webp",
    category: "places",
    orientation: "panorama",
    alt: "A panoramic view across columns, temples, and basilica ruins in the Roman Forum.",
    focalPoint: "53% 55%",
    recommendedFor: ["masthead", "timeline", "section divider"],
    source: {
      title: "Forum romanum 6k (5760x2097)",
      pageUrl:
        "https://commons.wikimedia.org/wiki/File:Forum_romanum_6k_(5760x2097).jpg",
      author: "BeBo86",
      license: "CC BY-SA 3.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
      originalDimensions: "5760 × 2097",
    },
  },
  {
    id: "constantine-night",
    name: "Arch of Constantine at night",
    path: "/assets/roman/places/constantine-night.webp",
    category: "places",
    orientation: "landscape",
    alt: "The Arch of Constantine illuminated against a deep blue night sky.",
    focalPoint: "50% 46%",
    recommendedFor: ["evening program", "dark-mode hero", "gala page"],
    source: {
      title: "Arch of Constantine at Night (Rome)",
      pageUrl:
        "https://commons.wikimedia.org/wiki/File:Arch_of_Constantine_at_Night_(Rome).jpg",
      author: "Livioandronico2013",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      originalDimensions: "5780 × 3814",
    },
  },
  {
    id: "pantheon-oculus",
    name: "Pantheon oculus",
    path: "/assets/roman/places/pantheon-oculus.webp",
    category: "places",
    orientation: "landscape",
    alt: "The coffered dome and bright central oculus inside the Pantheon.",
    focalPoint: "51% 35%",
    recommendedFor: ["keynote feature", "light motif", "dark background"],
    source: {
      title: "Interior oculus of the Rome Pantheon",
      pageUrl:
        "https://commons.wikimedia.org/wiki/File:Interior_oculus_of_the_Rome_Pantheon.jpg",
      author: "T. Le Berre",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      originalDimensions: "5472 × 3080",
    },
  },
  {
    id: "orange-theatre",
    name: "Roman Theatre of Orange",
    path: "/assets/roman/places/orange-theatre.webp",
    category: "places",
    orientation: "panorama",
    alt: "A wide view across the stone seating and stage wall of the Roman Theatre of Orange.",
    focalPoint: "51% 58%",
    recommendedFor: ["program hero", "speaker lineup", "wide card"],
    source: {
      title: "Roman Theatre in Orange 2008",
      pageUrl:
        "https://commons.wikimedia.org/wiki/File:Roman_Theatre_in_Orange_2008.jpg",
      author: "Benh LIEU SONG",
      license: "CC BY-SA 2.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0",
      originalDimensions: "6546 × 3273",
    },
  },
  {
    id: "caracalla-baths",
    name: "Baths of Caracalla",
    path: "/assets/roman/places/caracalla-baths.webp",
    category: "places",
    orientation: "landscape",
    alt: "Massive red-brick walls and open arches at the Baths of Caracalla.",
    focalPoint: "60% 45%",
    recommendedFor: [
      "architecture card",
      "history section",
      "textured background",
    ],
    source: {
      title: "Part of the Baths of Caracalla November 2013",
      pageUrl:
        "https://commons.wikimedia.org/wiki/File:Part_of_the_Baths_of_Caracalla_November_2013.jpg",
      author: "Nick-D",
      license: "CC BY-SA 3.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
      originalDimensions: "3896 × 2924",
    },
  },
  {
    id: "germanicus-bust",
    name: "Bust of Germanicus",
    path: "/assets/roman/artifacts/germanicus-bust.webp",
    category: "artifacts",
    orientation: "portrait",
    alt: "A white marble portrait bust of Germanicus against a charcoal museum backdrop.",
    focalPoint: "50% 38%",
    recommendedFor: [
      "speaker placeholder",
      "portrait card",
      "editorial feature",
    ],
    source: {
      title: "Bust of Germanicus, front - Getty Museum (2021.66)",
      pageUrl:
        "https://commons.wikimedia.org/wiki/File:Bust_of_Germanicus,_front_-_Getty_Museum_(2021.66).jpg",
      author: "J. Paul Getty Museum",
      license: "CC0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
      originalDimensions: "9749 × 12141",
    },
  },
  {
    id: "laurel-head",
    name: "Laurel-crowned portrait",
    path: "/assets/roman/artifacts/laurel-head.webp",
    category: "artifacts",
    orientation: "square",
    alt: "A weathered marble portrait head wearing a carved laurel wreath.",
    focalPoint: "50% 47%",
    recommendedFor: ["laurel motif", "award card", "editorial portrait"],
    source: {
      title: "Marble head of a man wearing a laurel wreath MET DP147258",
      pageUrl:
        "https://commons.wikimedia.org/wiki/File:Marble_head_of_a_man_wearing_a_laurel_wreath_MET_DP147258.jpg",
      author: "The Metropolitan Museum of Art",
      license: "CC0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
      originalDimensions: "4000 × 4000",
    },
  },
  {
    id: "toga-statue",
    name: "Toga-clad figure",
    path: "/assets/roman/artifacts/toga-statue.webp",
    category: "artifacts",
    orientation: "portrait",
    alt: "A headless Roman marble statue with deeply folded toga drapery.",
    focalPoint: "50% 48%",
    recommendedFor: ["portrait panel", "drapery detail", "speaker background"],
    source: {
      title: "Roman Marble Toga Statue (28450694740)",
      pageUrl:
        "https://commons.wikimedia.org/wiki/File:Roman_Marble_Toga_Statue_(28450694740).jpg",
      author: "Gary Todd",
      license: "CC0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
      originalDimensions: "3456 × 5184",
    },
  },
  {
    id: "gold-laurel-wreath",
    name: "Ancient gold laurel wreath",
    path: "/assets/roman/artifacts/gold-laurel-wreath.webp",
    category: "artifacts",
    orientation: "portrait",
    alt: "A delicate ancient gold laurel wreath resting on a silver cinerary vessel.",
    focalPoint: "49% 34%",
    recommendedFor: ["award theme", "laurel motif", "detail card"],
    source: {
      title: "Silver cinerary vessel and gold laurel wreath",
      pageUrl:
        "https://commons.wikimedia.org/wiki/File:Silver_cinerary_vessel_and_gold_laurel_wreath_(3rd_%E2%80%93_2nd_cent._B.C.)_at_the_National_Archaeological_Museum_of_Athens_on_16_May_2018.jpg",
      author: "George E. Koronaios",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      originalDimensions: "4000 × 6000",
      accuracyNote:
        "This is a Hellenistic Greek funerary object from the 3rd–2nd century BCE, included as a clearly labeled classical laurel reference rather than a Roman artifact.",
    },
  },
  {
    id: "corinthian-capital",
    name: "Corinthian capital",
    path: "/assets/roman/artifacts/corinthian-capital.webp",
    category: "artifacts",
    orientation: "landscape",
    alt: "A carved Roman Corinthian capital with acanthus leaves and small figures.",
    focalPoint: "50% 52%",
    recommendedFor: [
      "architecture detail",
      "neutral card",
      "ornamental reference",
    ],
    source: {
      title: "Roman - Corinthian Capital - Walters 23188",
      pageUrl:
        "https://commons.wikimedia.org/wiki/File:Roman_-_Corinthian_Capital_-_Walters_23188.jpg",
      author: "Walters Art Museum",
      license: "Public domain",
      licenseUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
      originalDimensions: "1800 × 1504",
    },
  },
  {
    id: "constantine-relief",
    name: "Arch relief detail",
    path: "/assets/roman/artifacts/constantine-relief.webp",
    category: "artifacts",
    orientation: "landscape",
    alt: "Carved relief panels, medallions, and Corinthian columns on the Arch of Constantine.",
    focalPoint: "52% 48%",
    recommendedFor: ["detail banner", "pattern reference", "history card"],
    source: {
      title: "Detail Arch Constantine, Rome, Italy",
      pageUrl:
        "https://commons.wikimedia.org/wiki/File:Detail_Arch_Constantine,_Rome,_Italy.jpg",
      author: "Jebulon",
      license: "CC BY-SA 3.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
      originalDimensions: "3423 × 2449",
    },
  },
  {
    id: "roman-inscription",
    name: "Trajanic inscription",
    path: "/assets/roman/artifacts/roman-inscription.webp",
    category: "artifacts",
    orientation: "landscape",
    alt: "A weathered Latin inscription carved into a pale stone block at ancient Tyre.",
    focalPoint: "50% 52%",
    recommendedFor: ["typographic texture", "quote card", "history detail"],
    source: {
      title: "AlMedinaSite-Tyre-TraianInscription",
      pageUrl:
        "https://commons.wikimedia.org/wiki/File:AlMedinaSite-Tyre-TraianInscription_RomanDeckert03112019.jpg",
      author: "RomanDeckert",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      originalDimensions: "3923 × 3000",
    },
  },
  {
    id: "mosaic-floor",
    name: "Capitoline mosaic",
    path: "/assets/roman/artifacts/mosaic-floor.webp",
    category: "artifacts",
    orientation: "landscape",
    alt: "A geometric Roman floor mosaic made from red, black, ochre, and white tesserae.",
    focalPoint: "50% 50%",
    recommendedFor: ["pattern background", "section texture", "graphic crop"],
    source: {
      title: "Ancient Roman mosaic floor detail, Musei Capitolini",
      pageUrl:
        "https://commons.wikimedia.org/wiki/File:Ancient_Roman_mosaic_floor_(detail)_-_Sala_della_Lupa_-_Palazzo_dei_Conservatori_-_Musei_Capitolini_-_Rome_2016.jpg",
      author: "José Luiz",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      originalDimensions: "5184 × 3456",
    },
  },
  {
    id: "villa-mysteries-fresco",
    name: "Villa of the Mysteries fresco",
    path: "/assets/roman/artifacts/villa-mysteries-fresco.webp",
    category: "artifacts",
    orientation: "landscape",
    alt: "Figures in pale drapery painted across the vivid red walls of the Villa of the Mysteries.",
    focalPoint: "50% 50%",
    recommendedFor: ["vermilion accent", "editorial strip", "art card"],
    source: {
      title: "Roman fresco Villa dei Misteri Pompeii 004",
      pageUrl:
        "https://commons.wikimedia.org/wiki/File:Roman_fresco_Villa_dei_Misteri_Pompeii_004.jpg",
      author: "Unknown",
      license: "Public domain",
      licenseUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
      originalDimensions: "800 × 600",
    },
  },
  {
    id: "laurel-leaves",
    name: "Bay laurel leaves",
    path: "/assets/roman/materials/laurel-leaves.webp",
    category: "materials",
    orientation: "landscape",
    alt: "Glossy green leaves on a bay laurel branch in warm sunlight.",
    focalPoint: "53% 45%",
    recommendedFor: ["botanical crop", "award motif", "edge decoration"],
    source: {
      title: "Laurus nobilis (4)",
      pageUrl: "https://commons.wikimedia.org/wiki/File:Laurus_nobilis_(4).JPG",
      author: "Marija Gajić",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      originalDimensions: "3648 × 2736",
    },
  },
  {
    id: "olive-branch",
    name: "Olive branch",
    path: "/assets/roman/materials/olive-branch.webp",
    category: "materials",
    orientation: "landscape",
    alt: "Green olives and silvery leaves clustered on a sunlit branch.",
    focalPoint: "52% 49%",
    recommendedFor: ["peace motif", "botanical crop", "card background"],
    source: {
      title: "Des olives vertes sur leur branche",
      pageUrl:
        "https://commons.wikimedia.org/wiki/File:Des_olives_vertes_sur_leur_branche..jpg",
      author: "VautrinThomas",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      originalDimensions: "3264 × 2448",
    },
  },
  {
    id: "palm-fronds",
    name: "Fan palm fronds",
    path: "/assets/roman/materials/palm-fronds.webp",
    category: "materials",
    orientation: "landscape",
    alt: "A broad green fan palm frond opening against a dark botanical background.",
    focalPoint: "50% 52%",
    recommendedFor: ["frond motif", "dark botanical panel", "texture crop"],
    source: {
      title: "2016-07-31 Botanischer Garten Tübingen 067",
      pageUrl:
        "https://commons.wikimedia.org/wiki/File:2016-07-31_Botanischer_Garten_T%C3%BCbingen_067.jpg",
      author: "Yeerge",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0",
      originalDimensions: "4896 × 3264",
    },
  },
  {
    id: "travertine",
    name: "Weathered travertine",
    path: "/assets/roman/materials/travertine.webp",
    category: "materials",
    orientation: "landscape",
    alt: "A close view of rough, porous cream-colored travertine stone.",
    focalPoint: "50% 50%",
    recommendedFor: ["subtle background", "stone texture", "overlay"],
    source: {
      title: "Pudostsky kamen",
      pageUrl: "https://commons.wikimedia.org/wiki/File:Pudostsky_kamen.jpg",
      author: "Artem Topchiy",
      license: "Public domain",
      licenseUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
      originalDimensions: "2691 × 1773",
    },
  },
  {
    id: "carrara-marble",
    name: "Carrara marble",
    path: "/assets/roman/materials/carrara-marble.webp",
    category: "materials",
    orientation: "square",
    alt: "Fine cream and gray mineral texture across a slab of Carrara marble.",
    focalPoint: "50% 50%",
    recommendedFor: ["light surface", "subtle texture", "card background"],
    source: {
      title: "Carrara marble",
      pageUrl: "https://commons.wikimedia.org/wiki/File:Carrara_marble.jpg",
      author: "Solarence",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
      originalDimensions: "2536 × 2536",
    },
  },
  {
    id: "terracotta-roof",
    name: "Terracotta roof tiles",
    path: "/assets/roman/materials/terracotta-roof.webp",
    category: "materials",
    orientation: "landscape",
    alt: "Rows of warm red terracotta roof tiles viewed at a shallow angle.",
    focalPoint: "50% 56%",
    recommendedFor: ["warm texture", "vermilion background", "geometric crop"],
    source: {
      title: "Telhado de cerâmica",
      pageUrl:
        "https://commons.wikimedia.org/wiki/File:Telhado_de_cer%C3%A2mica.jpg",
      author: "Albertoleoncio",
      license: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0",
      originalDimensions: "4000 × 3000",
    },
  },
] as const satisfies readonly RomanAsset[];

export const ROMAN_ASSET_BY_ID = Object.fromEntries(
  ROMAN_ASSETS.map((asset) => [asset.id, asset]),
) as Record<string, (typeof ROMAN_ASSETS)[number]>;
